#
args = commandArgs(trailingOnly = T)
i1 = as.numeric(args[[1]])
eth <- c("EUR","AFR","AMR","EAS","SAS")
cur.dir <- paste0("/data/zhangh24/multi_ethnic/result/LD_simulation_new/",eth[i1],"/")
#system(paste0("cd /data/zhangh24/multi_ethnic/result/LD_simulation_new/",eth[i1],"/"))
system(paste0("rm -rf summary_out_rep"))
system(paste0("mkdir ",cur.dir,"summary_out_rep"))
system(paste0("cp ",cur.dir,"summary_out_rho_*_rep_* ",cur.dir,"summary_out_rep/."))
system(paste0("tar -zcvf ",cur.dir,"summary_out_rep.tar.gz ",cur.dir,"summary_out_rep"))