Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 1 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 1 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 1 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 1 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 1 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 2 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 2 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 2 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 2 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 2 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 3 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 3 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 3 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 3 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 3 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 4 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 4 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 4 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 4 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 4 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 5 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 5 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 5 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 5 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 5 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 6 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 6 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 6 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 6 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 6 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 7 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 7 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 7 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 7 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 7 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 8 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 8 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 8 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 8 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 8 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 9 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 9 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 9 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 9 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 9 5
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 10 1
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 10 2
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 10 3
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 10 4
Rscript /gpfs/gsfs11/users/zhangh24/temp_show/show_swarm.R 10 5
